<?php

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

$ns = $req_schedule[0]['request_number'] . ".PDF";
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('PT Infrastruktur Bisnis Sejahtera');
$pdf->SetTitle($req_schedule[0]['request_number']);

$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE.' 006', PDF_HEADER_STRING);

$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);


$pdf->SetMargins("10", "10", "10", "5");
// $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT, PDF_MARGIN_BOTTOM);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

$pdf->SetAutoPageBreak(FALSE, 0);

$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

$pdf->SetFont('Times', '', 11);

$pdf->AddPage('P', 'A4');

$fileSUP = './assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$manager_nik.'.png';
if(file_exists($fileSUP)){
    $approve_sup = '<img height="60" src="/assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$manager_nik.'.png"><br>
    <font size="8" align="center" valign="middle">Signature is generated by system.</font>';
    $apprv_date_sup = date('d.m.Y  H:i:s', strtotime($apprv1['updated_at']));
    $manager_name_ttd = $manager_name;
} else {
    $approve_sup = '';
    $apprv_date_sup = '';
    $manager_name_ttd = '';
    $manager_position = '';
}
$fileDIV = './assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$divhead_nik.'.png';
if(file_exists($fileDIV)){
    $approve_div = '<img height="60" src="/assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$divhead_nik.'.png"><br>
    <font size="8" align="center" valign="middle">Signature is generated by system.</font>';
    $apprv_date_div = date('d.m.Y H:i:s', strtotime($apprv2['updated_at']));
} else {
    $approve_div = '';
    $apprv_date_div = '';
    $divhead_name = '';
    $divhead_position = '';
}
if (!empty($hr_nik)){
    $fileHR = './assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$hr_nik.'.png';
    if(file_exists($fileHR)){
        $approve_hr = '<img height="60" src="/assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$hr_nik.'.png"><br>
        <font size="8" align="center" valign="middle">Signature is generated by system.</font>';
        $apprv_date_hr = date('d.m.Y  H:i:s', strtotime($apprv3['updated_at']));
    } else {
        $approve_hr = '';
        $apprv_date_hr = '';
    }
} else {
    $approve_hr = '';
    $apprv_date_hr = '';
}

$table_data = '';
foreach($schedule as $value){
    //ADDED 30.10.2023
    if (!empty($value->actual_date) || !empty($value->actual_in)){
        $value->check_in = $value->actual_in;
    }
    if (!empty($value->actual_date) || !empty($value->actual_out)){
        $value->check_out = $value->actual_out;
    }
    /////////////////

    $table_data .= '<tr>
        <td>'.date('d.m.Y', strtotime($value->date)).'</td>
        <td>'.$value->full_name.'</td>
        <td>'.$value->employee_id.'</td>
        <td>'.date('d.m.Y', strtotime($value->check_in_date)).'</td>
        <td>'.$value->check_in.'</td>
        <td>'.date('d.m.Y', strtotime($value->check_out_date)).'</td>
        <td>'.$value->check_out.'</td>
    </tr>';
}


$logo = 'IBS.png';
$banner_color = 'bgcolor="#282464"';
$font_color = 'white';
$group = 'IBS';

$html = '<font size="8">
<table border="1" cellspacing="1" cellpadding="1">
    <tr align="right" height="10px" '.$banner_color.'>
        <td width="20%" align="center">
            <img height="50" src="/assets/images/'.$logo.'">
        </td>
        <td colspan="2" width="60%" align="center">
            <br><br>
            <b><font color="'.$font_color.'" size="12">ASSIGNMENT TO WORK ON HOLIDAYS(S)</font></b>
            <br>
        </td>
        <td width="20%" align="right">
            <b><font color="'.$font_color.'" size="10">'.$req_schedule[0]['request_number'].'</font></b>
        </td>
    </tr>
</table>
<table border="1" cellpadding="5" width="100%" hight="20%">
    <tr>
        <td width="15%"><b>MANAGER NAME</b></td>
        <td width="5%">:</td>
        <td width="30%">'.$manager_name.'</td>
        <td width="15%"><b>DIVISION</b></td>
        <td width="5%">:</td>
        <td width="30%">'.$divisi.'</td>
    </tr>
    <tr>
        <td><b>COST CENTER</b></td>
        <td>:</td>
        <td>'.$cost_center.'</td>
        <td><b>GROUP</b></td>
        <td>:</td>
        <td>'.$group.'</td>
    </tr>
    <tr>
        <td colspan="6"><br><br>Below employee(s) is (are) assigned to work on holiday(s) due to heavy work load:<br></td>
    </tr>
</table>
<table border="1" cellpadding="2" align="center" width="100%" hight="20%">
    <tr>
        <th><b>DATE</b></th>
        <th><b>NAME</b></th>
        <th><b>Employee ID (NIK)</b></th>
        <th><b>START DATE</b></th>
        <th><b>START TIME</b></th>
        <th><b>FINISH DATE</b></th>
        <th><b>FINISH TIME</b></th>
    </tr>'.
    $table_data
    .'
    <tr>
        <td colspan="7" align="left"><u><br>PURPOSE OF WORKING ON HOLIDAY(S):<br><br>'.$req_schedule[0]['ket'].'
        <br><br><br><br>LOCATION OF WORK:
        <br><br>'.$req_schedule[0]['lokasi'].'<br></u></td>
    </tr>
</table>
<table border="1" cellpadding="2">
    <tr>
        <td width="25%" align="center" colspan="2"><br><br><u>DIBUAT OLEH KARYAWAN:</u>
        <br><i>Prepared by Employee :</i><br>
        </td>
        <td width="25%" align="center"><br><br><u>DIKETAHUI OLEH MANAGER:</u>
        <br><i>Acknowledged by Manager :</i><br>
        </td>
        <td width="25%" align="center"><br><br><u>DISETUJUI OLEH DIV. HEAD:</u>
        <br><i>Approved by Div. Head :</i><br>
        </td>
        <td width="25%" align="center"><br><br><u>DIPERIKSA OLEH HR:</u>
        <br><i>Verified by HR :</i><br>
        </td>
    </tr>
    <tr>
        <td width="25%" align="center" colspan="2"><br><br>
            <img height="60" src="/assets/images/qrcode_tm_schedule/'.$req_schedule[0]['request_number'].'-'.$req_schedule[0]['nik'].'.png"><br>
            <font size="8" align="center" valign="middle">Signature is generated by system.</font><br>
        </td>
        <td width="25%" align="center"><br><br>
            '.
            $approve_sup
            .'<br>
        </td>
        <td width="25%" align="center"><br><br>
            '.
            $approve_div
            .'<br>
        </td>
        <td width="25%" align="center"><br><br>
            '.
            $approve_hr
            .'<br>
        </td>
    </tr>
    <tr>
        <td align="left" width="7%">Nama<br><i>Name</i></td>
        <td align="center" width="18%"><b>'.$full_name.'</b></td>
        <td align="center" width="25%"><b>'.$manager_name_ttd.'</b></td>
        <td align="center" width="25%"><b>'.$divhead_name.'</b></td>
        <td align="center" width="25%"><b>'.$hr_name.'</b></td>
    </tr>
    <tr>
        <td align="left" width="7%">Jabatan<br><i>Title</i></td>
        <td align="center" width="18%">'.$jabatan.'</td>
        <td align="center" width="25%">'.$manager_position.'</td>
        <td align="center" width="25%">'.$divhead_position.'</td>
        <td align="center" width="25%">'.$hr_position.'</td>
    </tr>
    <tr>
        <td align="left" width="7%">Tanggal<br><i>Date</i></td>
        <td align="center" width="18%">'. date('d.m.Y  H:i:s', strtotime($req_form[0]['revised_at'])) .'</td>
        <td align="center" width="25%">'. $apprv_date_sup .'</td>
        <td align="center" width="25%">'. $apprv_date_div .'</td>
        <td align="center" width="25%">'. $apprv_date_hr .'</td>
    </tr>
    <tr>
        <td colspan="5">
            <u>NOTE :</u><br>
            * The approval from Division Head must be obtained PRIOR TO overtime execution.<br>
            * Authorized signiturers could not be delegated.<br>
            * Submit the approved form to HR.
        </td>
    </tr>
</table>
</font>
</body>
</html>';

$pdf->writeHTML($html, true, false, false, false, '');

$pdf->Output($ns, 'I');
?>