<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<title>Surat Pengunduran Diri</title>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: "Times New Roman", Times, serif;
        font-size: 12pt;
        line-height: 1.15;
        color: #000;
    }
    p {
        margin: 0;
        text-indent: 0;
        text-align: justify;
    }
    .signature {
        margin-top: 150px;
        margin-left: 0px;
        padding-left: 0px;
    }
    .closing {
        margin-top: 50px;
        margin-left: 0px;
    }
    .placeholder {
        font-weight: bold;
    }
</style>
<?php
$paragraf2 = "Sebelumnya saya menyampaikan terima kasih atas kesempatan yang diberikan kepada saya
        selama bekerja dan berkarya di PT Infrastruktur Bisnis Sejahtera. Terima kasih atas
        bimbingan yang selama ini diberikan. Permohonan maaf saya sampaikan atas kekurangan
        saya selama <span>$working_year</span> tahun
        <span>$working_month</span> bulan";
    $qr = false;
    $file_path = FCPATH . 'assets/documents/document_resignation/'.$nik.'/resignation_letter/qrcode.png';
    if (file_exists($file_path)){
        $qr = true;
        $imgqr = $file_path;
    }
?>
</head>

<body>
    <p>Jakarta, <span><?=$date?></span></p>
    <p>Yth.<br>Bapak/Ibu <span><?=$division_head?></span><br>PT Infrastruktur Bisnis Sejahtera (IBS)<br>di Jakarta</p>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td height="5"></td>
        </tr>
    </table>
    <p>Yang bertanda tangan di bawah ini:</p>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td height="5"></td>
        </tr>
    </table>
    <table border="0" cellspacing="0" cellpadding="0" width="100%" class="identity">
        <tr>
            <td width="95">Nama</td>
            <td width="16">:</td>
            <td width="*"><span><?=$complete_name?></span></td>
        </tr>
        <tr>
            <td>Posisi</td>
            <td>:</td>
            <td><span><?=$position?></span></td>
        </tr>
        <tr>
            <td>Divisi</td>
            <td>:</td>
            <td><span><?=$division?></span></td>
        </tr>
        <tr>
            <td>NIK Karyawan</td>
            <td>:</td>
            <td><span><?=$nik?></span></td>
        </tr>
    </table>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td height="5"></td>
        </tr>
    </table>

    <p>Melalui surat ini, saya bermaksud mengajukan permohonan pengunduran diri dari perusahaan terhitung <span><?=$notice_period?></span> bulan dari tanggal <span class="placeholder"><?=$resignation_date?></span>.</p>

    <p><?=$paragraf2?></p>

    <p>Dalam masa pemberitahuan pengunduran diri saya, saya bersedia menyelesaikan semua tanggung
        jawab saya terhadap perusahaan, serta mengikuti ketentuan, tata tertib, dan etika kerja
        yang berlaku sesuai dengan Peraturan Perusahaan.</p>

    <p>Demikian surat pengunduran diri kerja ini saya buat dengan penuh kesadaran serta atas
        keinginan sendiri dan tanpa ada paksaan dari siapa pun.</p>

    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td height="20"></td>
        </tr>
    </table>
    <div>
        <div class="closing" style="text-align: start; width: 20px; margin-bottom: 10px;">Hormat saya,</div>
    </div>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="margin-top: 10px; padding: 0;">
        <tr>
            <td height="70" style="vertical-align: middle; margin: 0; padding: 0;">

                <?php if($qr): ?>

                    <table align="left" border="0" cellpadding="0" cellspacing="0" style="width: 150px; margin: 0; padding: 0;">
                        <tr style="padding-top: 8px; vertical-align:center ">
                            <td style="padding:0; ">
                                <img
                                    src="<?= $imgqr ?>"
                                    alt="QR Code"
                                    width="65"
                                    height="65"
                                    style="display: block;"
                                >
                            </td>
                        </tr>
                    </table>

                <?php endif; ?>

            </td>
        </tr>
        <?php if($qr): ?>
        <tr>
            <td style="
                padding: 8px 0 0 0;
                font-size: 8pt;
                line-height: 1.2;
                white-space: nowrap;
            ">
                Signature generated by system
            </td>
        </tr>
        <?php endif; ?>
    </table>
    <div>
        <div class="signature" style="text-align: start; width: 20px; margin-top: 10px;"><span><?=$complete_name?></span></div>
    </div>
    

    <div class="cc"><span style="font-style: italic;">Tembusan:</span><br>HR Department</div>

</body>
</html>