<?php

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

$ns = $req_schedule[0]['request_number'] . ".PDF";
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('PT Infrastruktur Bisnis Sejahtera');
$pdf->SetTitle($req_schedule[0]['request_number']);

$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE.' 006', PDF_HEADER_STRING);

$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);


$pdf->SetMargins("10", "10", "10", "5");
// $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT, PDF_MARGIN_BOTTOM);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

$pdf->SetAutoPageBreak(FALSE, 0);

$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

$pdf->SetFont('Times', '', 11);

$pdf->AddPage('P', 'A4');

$fileSUP = './assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$manager_nik.'.png';
if(file_exists($fileSUP)){
    $approve_sup = '<img height="60" src="/assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$manager_nik.'.png"><br>
    <font size="8" align="center" valign="middle">Signature is generated by system.</font>';
    $apprv_date_sup = date('d.m.Y  H:i:s', strtotime($apprv1['updated_at']));
} else {
    $approve_sup = '';
    $apprv_date_sup = '';
    $manager_name = '';
    $manager_position = '';
}
$fileDIV = './assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$divhead_nik.'.png';
if(file_exists($fileDIV)){
    $approve_div = '<img height="60" src="/assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$divhead_nik.'.png"><br>
    <font size="8" align="center" valign="middle">Signature is generated by system.</font>';
    $apprv_date_div = date('d.m.Y H:i:s', strtotime($apprv2['updated_at']));
} else {
    $approve_div = '';
    $apprv_date_div = '';
    $divhead_name = '';
    $divhead_position = '';
}

if (!empty($hr_nik)){
    $fileHR = './assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$hr_nik.'.png';
    if(file_exists($fileHR)){
        $approve_hr = '<img height="60" src="/assets/images/qrcode_tm_schedule/appr-'.$req_schedule[0]['request_number'].'-'.$hr_nik.'.png"><br>
        <font size="8" align="center" valign="middle">Signature is generated by system.</font>';
        $apprv_date_hr = date('d.m.Y  H:i:s', strtotime($apprv3['updated_at']));
    } else {
        $approve_hr = '';
        $apprv_date_hr = '';
    }
} else {
    $approve_hr = '';
    $apprv_date_hr = '';
}

$table_data = '';
$totalA = $totalB = $totalC = 0;
foreach($schedule as $value){
    if ($value->schedule_code == 'DO' || $value->dws == 'DON' || $value->dws == 'CTB'){
        $color = 'bgcolor="#dcdcdc"';
    } else {
        $color = '';
    }

    //ADDED 19.10.2023
    if (!empty($value->actual_date) || !empty($value->actual_in)){
        $value->check_in = $value->actual_in;
    }
    if (!empty($value->actual_date) || !empty($value->actual_out)){
        $value->check_out = $value->actual_out;
    }
    if (!empty($value->actual_date) || !empty($value->actual_type)){
        $value->shift_type = $value->actual_type;
    }
    /////////////////

    if(!empty($value->check_in) || !empty($value->check_out)){
        if($value->shift_type == 'A'){
            $checkA = '3';
            $checkB = '';
            $checkC = '';
            $totalA += 1;
        } else if ($value->shift_type == 'B'){
            $checkA = '';
            $checkB = '3';
            $checkC = '';
            $totalB += 1;
        } else if ($value->shift_type == 'C'){
            $checkA = '';
            $checkB = '';
            $checkC = '3';
            $totalC += 1;
        } else {
            $checkA = '';
            $checkB = '';
            $checkC = '';
        }
    } else {
        $checkA = '';
        $checkB = '';
        $checkC = '';
    }

    // ADDED 19.10.2023
    if (!empty($value->time_off_code)){
        $ket = $value->time_off;
    } else {
        $ket = $value->dws;
    }
    // ////////////////

    $table_data .= '<tr '.$color.'>
        <td>'.date('d.m.Y', strtotime($value->date)).'</td>
        <td>'.$value->schedule_in.'</td>
        <td>'.$value->schedule_out.'</td>
        <td>'.$value->check_in.'</td>
        <td>'.$value->check_out.'</td>
        <td><font face="zapfdingbats">'.$checkA.'</font></td>
        <td><font face="zapfdingbats">'.$checkB.'</font></td>
        <td><font face="zapfdingbats">'.$checkC.'</font></td>
        <td>'.$ket.'</td>
    </tr>';
}


$logo = 'logo-ibsw-5.png';
$banner_color = 'bgcolor="#D3D3D3"';
$font_color = 'black';

$html = '<font size="8">
<table border="1" cellspacing="1" cellpadding="1">
    <tr align="right" height="10px" '.$banner_color.'>
        <td width="20%" align="center">
            <br><br>
            <img height="50" src="/assets/images/'.$logo.'">
        </td>
        <td colspan="2" width="60%" align="center">
            <br><br>
            <b><font color="'.$font_color.'" size="10">FORMULIR KERJA SHIFT DAN LEMBUR<br>
            <i>Shift And Overtime Form</i></font></b>
            <br>
        </td>
        <td width="20%" align="center">
            <br><br><br>
            <b><font color="'.$font_color.'" size="8">'.$req_schedule[0]['request_number'].'</font></b>
        </td>
    </tr>
</table>
<table border="1" cellpadding="5" width="100%" hight="20%">
    <tr>
        <td width="15%"><b>NIK</b></td>
        <td width="5%">:</td>
        <td width="30%">'.$req_schedule[0]['nik'].'</td>
        <td width="15%"><b>JABATAN</b></td>
        <td width="5%">:</td>
        <td width="30%">'.$jabatan.'</td>
    </tr>
    <tr>
        <td><b>NAMA</b></td>
        <td>:</td>
        <td>'.$full_name.'</td>
        <td><b>DIVISI</b></td>
        <td>:</td>
        <td>'.$divisi.'</td>
    </tr>
</table>
<table border="1" cellpadding="2" align="center" width="100%" hight="20%">
    <tr>
        <th rowspan="2" width="15%"><b>TANGGAL</b></th>
        <th colspan="2" width="20%"><b>PLANNED</b></th>
        <th colspan="2" width="20%"><b>ACTUAL</b></th>
        <th colspan="3" width="25%"><b>SHIFT</b></th>
        <th rowspan="2" width="20%"><b>KETERANGAN</b></th>
    </tr>
    <tr>
        <td><b>IN</b></td>
        <td><b>OUT</b></td>
        <td><b>IN</b></td>
        <td><b>OUT</b></td>
        <td><b>A</b></td>
        <td><b>B</b></td>
        <td><b>C</b></td>
    </tr>'.
    $table_data
    .'
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><b>Total</b></td>
        <td><b>'.$totalA.'</b></td>
        <td><b>'.$totalB.'</b></td>
        <td><b>'.$totalC.'</b></td>
        <td></td>
    </tr>
</table>
<table border="1" cellpadding="2">
    <tr>
        <td width="25%" align="center" colspan="2"><br><br><u>DIBUAT OLEH KARYAWAN:</u>
        <br><i>Prepared by Employee :</i><br>
        </td>
        <td width="25%" align="center"><br><br><u>DIKETAHUI OLEH MANAGER:</u>
        <br><i>Acknowledged by Manager :</i><br>
        </td>
        <td width="25%" align="center"><br><br><u>DISETUJUI OLEH DIV. HEAD:</u>
        <br><i>Approved by Div. Head :</i><br>
        </td>
        <td width="25%" align="center"><br><br><u>DIPERIKSA OLEH HR:</u>
        <br><i>Verified by HR :</i><br>
        </td>
    </tr>
    <tr>
        <td width="25%" align="center" colspan="2"><br><br>
            <img height="60" src="/assets/images/qrcode_tm_schedule/'.$req_schedule[0]['request_number'].'-'.$req_schedule[0]['nik'].'.png"><br>
            <font size="8" align="center" valign="middle">Signature is generated by system.</font><br>
        </td>
        <td width="25%" align="center"><br><br>
            '.
            $approve_sup
            .'<br>
        </td>
        <td width="25%" align="center"><br><br>
            '.
            $approve_div
            .'<br>
        </td>
        <td width="25%" align="center"><br><br>
            '.
            $approve_hr
            .'<br>
        </td>
    </tr>
    <tr>
        <td align="left" width="7%">Nama<br><i>Name</i></td>
        <td align="center" width="18%"><b>'.$full_name.'</b></td>
        <td align="center" width="25%"><b>'.$manager_name.'</b></td>
        <td align="center" width="25%"><b>'.$divhead_name.'</b></td>
        <td align="center" width="25%"><b>'.$hr_name.'</b></td>
    </tr>
    <tr>
        <td align="left" width="7%">Jabatan<br><i>Title</i></td>
        <td align="center" width="18%">'.$jabatan.'</td>
        <td align="center" width="25%">'.$manager_position.'</td>
        <td align="center" width="25%">'.$divhead_position.'</td>
        <td align="center" width="25%">'.$hr_position.'</td>
    </tr>
    <tr>
        <td align="left" width="7%">Tanggal<br><i>Date</i></td>
        <td align="center" width="18%">'. date('d.m.Y  H:i:s', strtotime($req_form[0]['revised_at'])) .'</td>
        <td align="center" width="25%">'. $apprv_date_sup .'</td>
        <td align="center" width="25%">'. $apprv_date_div .'</td>
        <td align="center" width="25%">'. $apprv_date_hr .'</td>
    </tr>
    <tr>
        <td colspan="5">
            <u>Notes :</u><br>
            - Formulir ini harus diserahkan ke HR paling lambat tanggal 10 setiap bulannya.<br>
            - <i>This form has to be submitted to HR latest on the 10th of every month.</i><br>
            - DILARANG MERUBAH/MENDUPLIKASI Form ini ke Format yang lain. Gunakan Form ini untuk mengisi jadwal shift Anda.<br>
            - <i>DO NOT Change or Copy This Form to another format. Use only this Form to fill your Shift Schedule.</i>
        </td>
    </tr>
</table>
</font>
</body>
</html>';

$pdf->writeHTML($html, true, false, false, false, '');

$pdf->Output($ns, 'I');
?>