<?php
//============================================================+
// File name   : example_006.php
// Begin       : 2008-03-04
// Last Update : 2013-05-14
//
// Description : Example 006 for TCPDF class
//               WriteHTML and RTL support
//
// Author: Nicola Asuni
//
// (c) Copyright:
//               Nicola Asuni
//               Tecnick.com LTD
//               www.tecnick.com
//               info@tecnick.com
//============================================================+


//dumper($img);

/**
 * Creates an example PDF TEST document using TCPDF
 * @package com.tecnick.tcpdf
 * @abstract TCPDF - Example: WriteHTML and RTL support
 * @author Nicola Asuni
 * @since 2008-03-04
 */
		
//dumper(decrypt($header[0]->complete_name));
// create new PDF document

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$ns = str_replace("/","","");
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('PT Inti Bangun Sejahtera Tbk');
// $pdf->SetTitle("HRIS-TM-".$header[0]->request_number);
// $pdf->SetSubject("HRIS-TM".$header[0]->request_number);
// $pdf->SetKeywords('HRIS-TM,IBS');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE.' 006', PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins("25", "10", "25");
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)

$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
// ---------------------------------------------------------

// set font
$pdf->SetFont('Times', '', 11);


// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Print a table

// add a page
$pdf->AddPage('P', 'A4');

if (!empty($divhead_name)){
    $nik_atasan = $divhead_nik;
    $nama_atasan = $divhead_name;
    $judul_atasan = 'Kepala Divisi';
} else {
    $nik_atasan = $director_nik;
    $nama_atasan = $director_name;
    $judul_atasan = 'Direktur';
}


$logo = '<img height="75" src="/assets/images/ibsw_TM.png">';

$file = '/assets/images/qrcode_tm/appr-'.$req_to[0]['request_number'].'-'.$nik_atasan.'.png';
if(file_exists('.'.$file)){
    $approve_div = '<img height="60" src="/assets/images/qrcode_tm/appr-'.$req_to[0]['request_number'].'-'.$nik_atasan.'.png"><br>
    <font size="8" align="center" valign="middle">Signature is generated by system.</font>';
} else {
    $approve_div = '';
}

$html = '<font size="12">
<table align="center">
    <tr align="center" height="10px">
        <td width="100%" align="center">
            '.$logo.'
        </td>
    </tr>
</table>
<br>
<hr>
<table>
    <tr>
        <td></td>
    </tr>
    <tr>
        <td></td>
    </tr>
    <tr align="center">
        <td><h1><u>SURAT PERMOHONAN DISPENSASI</u></h1></td>
    </tr>
</table>
<br>
<br>
<br>
<table>
    <tr>
        <td></td>
    </tr>
    <tr>
        <td>Yang bertanda tangan di bawah ini:</td>
    </tr>
    <tr>
        <td></td>
    </tr>
</table>
<table>
    <tr align="justify">
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Sehubungan dengan pemeriksaan pencatatan data absensi kehadiran saya di Perusahaan '.$company_name.' bahwa terdapat data absensi saya atas nama '.$full_name.' yang masih tidak masuk/tercatat dalam pencatatan <i>record</i> absensi di <i>system HRD</i> perusahaan sebanyak 1 (satu) hari pada tanggal '.$date.'
        </td>
    </tr>
    <tr>
        <td></td>
    </tr>
    <tr align="justify">
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Sehubungan dengan pemeriksaan tersebut, bersama surat ini disampaikan permohonan dispensasi atau keringanan untuk tidak dilakukan pemotongan cuti dikarenakan '.$req_to[0]['note'].'. Mengingat pentingnya data absensi ini, kami mohon agar dapat memenuhi permohonan kami ini. Apabila selama 1 bulan lebih dari 3 hari, saya melakukan kelalaian yang sama maka dengan sendirinya saya bersedia untuk dilakukan pemotongan cuti sampai dengan upah tidak dibayar oleh perusahaan <i><b>no work no pay</b></i> sesuai minus cuti saya.
        </td>
    </tr>
    <tr>
        <td></td>
    </tr>
    <tr align="justify">
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Demikian surat permohonan dispensasi ini kami buat. Atas perhatian dan kerja sama Bapak, kami ucapkan terima kasih.
        </td>
    </tr>
    <tr>
        <td></td>
    </tr>
    <tr>
        <td></td>
    </tr>
    <tr>
        <td></td>
    </tr>
</table>
<table>
    <tr>
        <td>Jakarta, '.$create_date.'</td>
    </tr>
    <tr>
        <td></td>
    </tr>
    <tr>
        <td></td>
    </tr>
</table>
<table  >
    <tr>
        <td align="center">Dibuat, </td>
        <td align="center">Disetujui, </td>
    </tr>
    <tr>
        <td align="center"></td>
        <td align="center"></td>
    </tr>
    <tr>
    <td width="50%" align="center">
        <img height="60" src="/assets/images/qrcode_tm/'.$req_to[0]['request_number'].'-'.$req_to[0]['nik'].'.png"><br>
        <font size="8" align="center" valign="middle">Signature is generated by system.</font>
    </td>
    <td width="50%" align="center">
        '.
        $approve_div
        .'
    </td>
    </tr>
    <tr>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td align="center"><u><b>'.$full_name.'</b></u></td>
        <td align="center"><u><b>'.$nama_atasan.'</b></u></td>
    </tr>
    <tr>
        <td align="center"><b>Karyawan </b></td>
        <td align="center"><b>'.$judul_atasan.'</b></td>
    </tr>
</table>
</font>
</body>
</html>';
// $html = $nosurat;
// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output($ns, 'I');
//============================================================+
// END OF FILE
//============================================================+